---
name: default
type: docker
kind: pipeline


steps:
  - name: test
    image: python:3.8
    commands:
      - pip install pipenv
      - pipenv install --dev -v
      - pipenv run pytest -cov-report=xml --cov=jsd_mp
      - pipenv run mypy jsd_mp
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - jsd_mp.xml
