---
name: default
type: docker
kind: pipeline


steps:
  - name: test
    image: python
    commands:
      - pip install pipenv
      - pipenv install --dev -v
      - pipenv run pytest
      - pipenv run mypy jsd_mp
